---
- apt_key: id=C7A7DA52 keyserver=keyserver.ubuntu.com state=present

- apt_repository: repo='deb http://apt.datadoghq.com/ stable main' state=present update_cache=yes

- apt: name=datadog-agent state=latest

- template: src=datadog.conf.j2 dest=/etc/dd-agent/datadog.conf
  notify: restart datadog

- template: src=process.yaml.j2 dest=/etc/dd-agent/conf.d/process.yaml
  when: datadog_process_checks is defined
  notify: restart datadog

- service: name=datadog-agent state=started enabled=yes
  when: datadog_enabled

- service: name=datadog-agent state=stopped enabled=no
  when: not datadog_enabled
