---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: win2012
    box: opentable/win-2012r2-standard-amd64-nocm
    memory: 2048
provisioner:
  name: ansible
  inventory:
    host_vars:
      win2012:
        ansible_become: false
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_port: 5985
        ansible_host: 127.0.0.1
        ansible_connection: winrm
        ansible_winrm_scheme: http
        ansible_winrm_server_cert_validation: ignore
    group_vars:
      linux:
        ansible_become: true
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0013
verifier:
  name: testinfra
  lint:
    name: flake8
